### ISSUE TITLE
I'm not seeing the "download" icon once I've chosen a song

### ISSUE THREAD

**Issue by memarkham303** [amcolash/flowkey-scraper#2] opened 2021-07-14 01:41 UTC
Hi Andrew,

Just a heads-up that after updating to 0.10 today, I'm no longer seeing the "download" icon in the upper-right corner.

I moved back to 0.09, which I had previously used successfully, but there's no download icon from that version either. 

I wonder if FlowKey has changed something about their UI that's blocking your download icon.  
![Screen Shot 2021-07-13 at 19 40 49 PM](https://user-images.githubusercontent.com/43356164/125547136-c05bd979-b527-4a3f-86fe-de770a7af928.png)

I am so grateful for your app.. a real life-saver.

**Comment by amcolash** [comment] 2021-07-20 03:57
It looks like it was an intermittent issue caused by the loading spinner and fading in changing a bit. Should be fixed with v0.11.0. If it is still an issue please re-open.

**Closed as completed by amcolash** 2021-07-20 03:57 UTC

**Comment by memarkham303** [comment] 2021-07-21 21:48
You da man!  Ver 0.11.0 corrected the problem.  Thank you so much.
